const femaleNames: string[] = [
  "Agune",
  "Beatrice",
  "Breagan",
  "Bronwyn",
  "Cannora",
  "Drelil",
  "Elgile",
  "Esme",
  "Griya",
  "Henaine",
  "Lirann",
  "Lirathil",
  "Lisabeth",
  "Moralil",
  "Morgwen",
  "Sybil",
  "Theune",
  "Wenain",
  "Ygwal",
  "Yslen",
];

const maleNames: string[] = [
  "Arwel",
  "Bevan",
  "Boroth",
  "Borrid",
  "Breagle",
  "Breglor",
  "Canhoreal",
  "Emrys",
  "Ethex",
  "Gringle",
  "Grinwit",
  "Gruwid",
  "Gruwth",
  "Gwestin",
  "Mannog",
  "Melnax",
  "Orthax",
  "Triunein",
  "Wenlan",
  "Yirmeor",
];

const surnames: string[] = [
  "Abernathy",
  "Addercap",
  "Burl",
  "Candlewick",
  "Cormick",
  "Crumwaller",
  "Dunswallow",
  "Getri",
  "Glass",
  "Harkness",
  "Harper",
  "Loomer",
  "Malksmilk",
  "Smythe",
  "Sunderman",
  "Swinney",
  "Thatcher",
  "Tolmen",
  "Weaver",
  "Wolder",
];

const backgrounds: string[] = [
  "an alchemist",
  "a blacksmith",
  "a butcher",
  "a burglar",
  "a carpenter",
  "a cleric",
  "a gambler",
  "a gravedigger",
  "an herbalist",
  "a hunter",
  "a magician",
  "a mercenary",
  "a merchant",
  "a miner",
  "an outlaw",
  "a performer",
  "a pickpocket",
  "a smuggler",
  "a servant",
  "a ranger",
];

const physiques: string[] = [
  "a statuesque",
  "a brawny",
  "a towering",
  "a stout",
  "a rugged",
  "an athletic",
  "a lanky",
  "a short",
  "a scrawny",
  "a flabby",
];

const skins: string[] = [
  "dark",
  "a birthmark on your",
  "tanned",
  "pockmarked",
  "weathered",
  "oily",
  "pale",
  "perfect",
  "rosy",
  "tattooed",
];

const hairs: string[] = [
  "bald",
  "braided",
  "oily",
  "wavy",
  "curly",
  "long",
  "wispy",
  "filthy",
  "frizzy",
  "luxurious",
];

const faces: string[] = [
  "a chiseled",
  "a square",
  "a bony",
  "a sharp",
  "a sunken",
  "an elongated",
  "a broken",
  "a soft",
  "a rat-like",
  "a round",
];

const speeches: string[] = [
  "blunt",
  "booming",
  "droning",
  "gravelly",
  "cryptic",
  "formal",
  "stuttering",
  "precise",
  "squeaky",
  "whispery",
];

const clothings: string[] = [
  "antique",
  "bloody",
  "rancid",
  "soiled",
  "frumpy",
  "elegant",
  "frayed",
  "foreign",
  "livery",
  "filthy",
];

const virtues: string[] = [
  "ambitious",
  "courageous",
  "disciplined",
  "honorable",
  "serene",
  "merciful",
  "humble",
  "tolerant",
  "gregarious",
  "cautious",
];

const vices: string[] = [
  "aggressive",
  "bitter",
  "craven",
  "deceitful",
  "greedy",
  "vengeful",
  "lazy",
  "nervous",
  "rude",
  "vain",
];

const reputations: string[] = [
  "an oddball",
  "wise",
  "respected",
  "ambitious",
  "repulsive",
  "dangerous",
  "honest",
  "a boor",
  "a loafer",
  "an entertainer",
];

const misfortunes: string[] = [
  "abandoned",
  "addicted",
  "blackmailed",
  "condemned",
  "cursed",
  "defrauded",
  "demoted",
  "discredited",
  "disowned",
  "exiled",
];
